# TODO:

# - Create a Docker compose file that will have 4 services: nginx proxy, red, yellow and green app
# - All services should be on the same _external_ network
# - Only the nginx proxy should have an exposed port 80
# - All apps (except the proxy) should have a named volume mounted
# - All apps (except proxy) should be built when we run _docker compose up_
# - Nginx proxy should build the image from the nginx directory
# - All the other apps have their own set of instructions in each directory
# - Good luck!
version: '3.8'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - challenge-network
    depends_on:
      - red
      - yellow
      - green

  red:
    build:
      context: ./red
    volumes:
      - red-data:/app
    networks:
      - challenge-network

  yellow:
    build:
      context: ./yellow
    volumes:
      - yellow-data:/app
    networks:
      - challenge-network

  green:
    build:
      context: ./green
    volumes:
      - green-data:/app
    networks:
      - challenge-network
volumes:
  red-data:
  yellow-data:
  green-data:

networks:
  challenge-network:
    external: true
